name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Type check
      run: npx tsc --noEmit

    - name: Build application
      run: npm run build
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test-secret-key-for-ci' }}
        AWS_REGION: us-east-1

    - name: Run tests (if available)
      run: npm test --if-present

  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Check for vulnerabilities
      run: npx audit-ci --moderate
      continue-on-error: true

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code formatting
      run: npx prettier --check .
      continue-on-error: true

    - name: Bundle analyzer
      run: |
        npm run build
        npx @next/bundle-analyzer
      env:
        JWT_SECRET: test-secret-key-for-ci
        ANALYZE: true
      continue-on-error: true

  deployment-check:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test-secret-key-for-ci' }}
        AWS_REGION: us-east-1
        NODE_ENV: production

    - name: Check build artifacts
      run: |
        echo "Checking build output..."
        ls -la .next/
        echo "Build size analysis:"
        du -sh .next/

    - name: Validate environment template
      run: |
        echo "Validating environment configuration..."
        if [ ! -f "env.example" ]; then
          echo "❌ env.example file is missing"
          exit 1
        fi
        echo "✅ Environment template found"

    - name: Check security files
      run: |
        echo "Checking security documentation..."
        if [ ! -f "SECURITY.md" ]; then
          echo "❌ SECURITY.md file is missing"
          exit 1
        fi
        echo "✅ Security documentation found"